config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vagas.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vagas/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from .views import CandidatoSignUpView, EmpresaSignUpView, DashboardEmpresaView, DashboardCandidatoView
from django.urls import path
from . import views

# rota padrão
urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

# rota de vagas
urlpatterns += [
    path('vagas', views.VagaListView.as_view(), name='vaga-list'),
    path('vagas/nova/', views.VagaCreateView.as_view(), name='vaga-create'),
    path('vagas/<int:pk>/editar/', views.VagaUpdateView.as_view(), name='vaga-update'),
    path('vagas/<int:pk>/excluir/', views.VagaDeleteView.as_view(), name='vaga-delete'),
]

# rota de candaturas
urlpatterns += [
    path('candidatar/<int:vaga_id>/', views.CandidaturaCreateView.as_view(), name='candidatar'),
    path('candidaturas/recebidas/', views.CandidaturasRecebidasView.as_view(), name='candidaturas-recebidas'),
]

# rota de signup
urlpatterns += [
    path('signup/candidato/', CandidatoSignUpView.as_view(), name='signup_candidato'),
    path('signup/empresa/', EmpresaSignUpView.as_view(), name='signup_empresa'),
]

# rota de autenticação
urlpatterns += [
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
]

# rota dashboard
urlpatterns += [
    path('dashboard/empresa', DashboardEmpresaView.as_view(), name='dashboard-empresa'),
    path('dashboard/candidato', DashboardCandidatoView.as_view(), name='dashboard-candidato'),
]

app/models.py
import uuid

from django.db import models

class Person(models.Model):
    #person_id = models.UUIDField(primary_key=True, default=uuid.uuid4(), editable=False)
    name = models.CharField(max_length=100)
    age = models.IntegerField()

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    pages = models.IntegerField()
    published_date = models.DateField()

    def __str__(self):
        return (f"""{{
                "title" : "{self.title}",
                "author" : "{self.author}",
                "pages" : {self.author},
                "published_date" : "{self.published_date}"
                }}""")

app/templates/app/book_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirmar exclusão</title>
</head>
<body>
    <h1>Confirmar exclusão</h1>
    <p>Tem certeza que deseja excluir o livro "{{ book.title }}"</p>
    <form method="post" onsubmit="return confirm('Essa ação não terá retorno.')">
        {% csrf_token %}
        <button type="submit">Confirmar</button> <a href="{% url 'book_list' %}">Cancelar</a>
    </form>
</body>
</html>

app/templates/app/book_detail.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Detalhes do livro {{ book.title }}</title>
</head>
<body>
    <h1>Detalhes do livro {{ book.title }}</h1>
    <p>Autor: <strong>"{{ book.author }}"</strong></p>
    <p>Páginas: <strong>"{{ book.pages }}"</strong></p>
    <p>Publicado em: <strong>"{{ book.published_date }}"</strong></p>
    <a href="{% url 'book_list' %}">Voltar à lista</a>
</body>
</html>

app/templates/app/book_form.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>{% if book %}Editar{% else %}Cadastrar{% endif %} Livro</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
</head>
<body>
    <div class="container mb-5">
        <h1>{% if book %}Editar{% else %}Cadastrar{% endif %} Livro</h1>

        <form id="book-form" class="form" method="post">
            {% csrf_token %}
            {{ form.as_div }}
            <button type="submit">{% if book %}Atualizar{% else %}Cadastrar{% endif %}</button>
        </form>

        <p><a href="{% url 'book_list' %}">Voltar para a listagem de livros</a></p>
    </div>
</body>
    {% if book %}
    <script defer>
        document.addEventListener('DOMContentLoaded', function() {
            const form = document.getElementById('book-form');
            if (!form) return;

            form.addEventListener('submit', function(e) {
                e.preventDefault();

                const data = new FormData(form);
                const jsonData = Object.fromEntries(data.entries());

                fetch(window.location.href, {
                    method: 'PUT',
                    headers: {
                          'Content-Type': 'application/json',
                          'Accept': 'application/json',
                          'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify(jsonData)
                })
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Erro na atualização');
                    }
                    return response.json();
                })
                .then(data => {
                    alert('Atualizado com sucesso!');
                    window.location.href = "{% url 'book_list' %}";
                })
                .catch(error => {
                    console.error('Erro:', error);
                    alert('Falha ao atualizar.');
                });
            });
        });
    </script>
    {% endif %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</html>

app/templates/app/book_list.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Lista de Livros</title>
</head>
<body>
    <h1>Lista de Livros</h1>
    <ul>
        {% for book in books %}
            <li>{{ book.title }} - {{ book.author }} ({{ book.pages }} páginas) - <a href="/book/{{ book.id }}">detalhes</a> - <a href="/book/edit/{{ book.id }}">editar</a> - <a href="/book/delete/{{ book.id }}">excluir</a></li>
        {% empty %}
            <li>Nenhum livro cadastrado.</li>
        {% endfor %}
    </ul>
</body>
</html>

app/templates/app/contact.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Fale Conosco</title>
</head>
<body>
    {% if success %}
        <p>Obrigado, {{ name }}. Sua mensagem foi enviada!</p>
    {% else %}
    <h2>Fale Conosco</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_div }}
        <button type="submit">Enviar</button>
    </form>
    {% endif %}
</body>
</html>

app/templates/app/welcome.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Bem-vindo!</title>
</head>
<body>
    <h1>Olá, {{ name }}</h1>
</body>
</html>